plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.lensii.modules'
version = '1.0.0'

android {
  namespace "expo.modules.playbilling"
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}

dependencies {
  implementation 'com.android.billingclient:billing:9.1.0'
}
